---

- name: Change Junos Passwords
  connection: netconf
  gather_facts: false
  hosts: all
  vars_prompt:

    - name: deviceusername
      prompt: "Username of password to change?"
      private: no

    - name: devicepassword
      prompt: "New password? (Password hidden from CLI for security purposes - please paste in if you're having trouble)"
      private: yes
      encrypt: "md5_crypt"

    - name: commitcomment
      prompt: "Comment for commit?"
      private: no


  tasks:


    - name: Change password and do commit confirmed 5
      junos_config:
        comment: "{{ commitcomment }}"
        lines:
          - set system login user {{deviceusername}} authentication encrypted-password {{devicepassword}}
        confirm: 5
      when: ansible_network_os == 'junos'

    - name: Wait for ten seconds to confirm we haven't lost connectivity before continuing
      wait_for:
        timeout: 10

    - name: Commit config now we know we still have access
      junos_config:
        check_commit: yes
